### ISSUE TITLE
npm build:app does not put assets in /public/assets folder

### ISSUE THREAD

**Issue by jkt3000** [drannex42/svelte-capacitor#14]
While trying to get ios simulator working, I noticed that the script ```build:app``` does not move the assets in ```/assets``` into the ```/public/assets``` folder, it puts them into ```/public```. 

I notice this because the script ```build:ios``` calls ```build:app``` first before copying into the ```/ios/App/App``` folder. But when running the IOS simulator, I noticed that the svelte_cap.png would not load on the simulator, because it is referencing `/assets/svelte_cap.png` but that file is actually in ```ios/App/App/public/svelte_cap.png```.

I'm not sure what the expected behaviour is supposed to be, but I am thinking it's a problem in the ```build:app``` stage?

I also notice that following the readme guide for running on ios, `npm run dev:ios` initially presents a blank screen on the simulator. Nothing appear. If I build the app first `npm run build:ios` and then run `npm run dev:ios` I can at least see the screen - however no hot reloading works - which makes me believe that `npm run build:ios` is not the required step and that the ios simulator should of worked properly with just the `npm run dev:ios` command.  (This is how I first noticed that the assets weren't being copied into the /assets folder.)

**Comment by macleod-ee** [comment]
I have not been able to recreate the issue, I will look into this.

**Comment by mike-sheppard** [comment]
Hey @drannex42 thanks for this starter repo - just having a play with this at the moment.

Having a similar issue on Android with the `/assets/svelte_cap.png`. Seems the asset is not copied to the built `public` dir?

---

**Browser**

<img width="1068" alt="Screenshot 2021-08-15 at 18 55 39" src="https://user-images.githubusercontent.com/1690006/129487823-797f1730-b45d-46b0-b99b-930cba057c6f.png">

**Android**

![Screenshot_20210815-185647_Svelte Capacitor](https://user-images.githubusercontent.com/1690006/129487874-6004236b-b851-4ff4-947d-abb7fdcb4d29.jpg)

**Comment by macleod-ee** [comment]
This is expected, I made the mistake of referencing it as `/asset/` in the index.svelte (and in the readme!), anything added to `/assets` will be copied to `/public` verbatim, folder structure and all. 

If you add anything to assets that you want to reference please refer to it as `/svelte-cap.png` and not `/assets/svelte-cap.png` unless you add it to `/assets/assets/`.

I have not been able to test this on iOS so @redronin I would love to hear your feedback on this. 

I've also fixed the preproccesser in the latest version, please pull the latest version and report back if it fixes the issue.

**Comment by mike-sheppard** [comment]
all fixed in latest, nice one 👍🏻

**Comment by jkt3000** [comment]
I had to reference any assets in the public/assets folder as ```/item.png``` as well.
