### ISSUE TITLE
Error when trying to build for IOS

### ISSUE THREAD

**Issue by jkt3000** [drannex42/svelte-capacitor#17]
Running the command 
`npm run build:ios`

I get the following error
```
[error] Could not find the web assets directory: ./www.
        Please create it and make sure it has an index.html file. You can change the path of this directory in
        capacitor.config.json (webDir option). You may need to compile the web assets for your app (typically npm run
        build). More info: https://capacitorjs.com/docs/basics/workflow#sync-your-project
```

however, in my capacitor.config.json the webDir field is set to /public.

```
{
  "appId": "com.svelte.capacitor",
  "appName": "Svelte Capacitor",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "public",
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 0
    }
  },
  "cordova": {},
  "server": {
    // "url": "http://192.168.2.3:5000",
    "cleartext": true
  }
}
```

Not sure what to do here

**Comment by jkt3000** [comment]
If I move everything in ```/public``` to ```/www```, the `cap-run ios` command works fine. So I guess the config file is not being respected?

**Comment by jkt3000** [comment]
Ok, I have no idea why, but if I use a .ts config file, it seems to recognize the webDir public, and will work file.

I removed the `capacitor.config.json` file
Created a `capacitor.config.ts` file as shown below:
```
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.company.appname',
  appName: 'My Capacitor App',
  webDir: 'public',
  plugins: {
    SplashScreen: {
      launchShowDuration: 0
    }
  },
  cordova: {},
  server: {
    //url: "http://192.168.2.3:5000",
    cleartext: true
  }
};

export default config;
```

I can then run the ```npm run cap-run:ios``` command and will recognize the public web assets path build and launch xcode ok.

I saw that in capacitor 3.0 docs to create a config.ts file if you use typescript, although a json fiile should also work. Other settings in json file are recognized, so not sure why the webDir isn't.

**Comment by macleod-ee** [comment]
Yeah, this is a weird thing. I've come across similar in the older version, and seems to be a Capacitor.js related issue as far as my brief foray has shown. Issues in the past for capacitor all say you need to add the platform, built it first, and then it will work. 

https://github.com/ionic-team/capacitor/issues/1883 (2019)
https://github.com/ionic-team/ionic-cli/issues/4510 (2021)
> Just use ionic cap sync, then, use ionic cap build, work´s for me!!! 

You can replace ionic with npx as well, I guess. 

https://forum.ionicframework.com/t/not-able-to-find-webdir-directory-in-cap-3-config-file/211194

Seems to be a recurring thing on their side, I'll close this.
