### ISSUE TITLE
"If you're targeting iOS or both" readme instruction.

### ISSUE THREAD

**Issue by ogrotten** [drannex42/svelte-capacitor#18]
> If you're targeting iOS or both, you will need to _append_ your workstation IP to the server.url section in capacitor.config.json instead.

What does this look like for example? There's a lot of ways that "append" here could work.

**Comment by macleod-ee** [comment]
You need to replace the "change-me" value to your IP address in capacitor.config.json, I'm sure there's a better wording that could be used but this was the best version we came up with for clarity between myself and two other documentation contributors. 

```
  "server": {
      "url": "http://change-me:5001",
      "cleartext": true
  }
```

I'll go ahead and mark this as closed.
