### ISSUE TITLE
Vite fails to start server - Failed to resolve entry for package "@roxi/routify > @types/node"

### ISSUE THREAD

**Issue by kaashyapan** [drannex42/svelte-capacitor#19]
I cloned the template 
```
npm i
npm run dev:start

Error: Failed to resolve entry for package "@roxi/routify > @types/node". The package may have incorrect main/module/exports specified in its package.json: 
Failed to resolve entry for package "@roxi/routify > @types/node". The package may have incorrect main/module/exports specified in its package.json.
```

I have checked for possible issues reported in the vite repo & routify repo and found none.
Can you confirm if this is not a problem with the config in this template and possibly point me to a resolution ?

**Comment by patrickjquinn** [comment]
I'm seeing this as of today. AFIK there has been a vite upgrade that doesnt like what ever horse manure way routify is exporting its interface. Might be best to pin the Vite version for the time being.

**Comment by garlandcrow** [comment]
Actually its the `@sveltejs/vite-plugin-svelte` update that is the culprit, pin to `1.0.0-next.19` and it will work again.

**Comment by kaashyapan** [comment]
Wonderful thanks for your advice.
Works alright
