### ISSUE TITLE
How do I run Electron?

### ISSUE THREAD

**Issue by Freiza** [drannex42/svelte-capacitor#2]
How do I run Electron?
There is nothing mentioned in package.json.
Edit:
I managed to run electron using.
npx cap open electron.
but I see only a blank page.

**Comment by macleod-ee** [comment]
There were a few bugs with electron when this was released, I have a few fixes but those are only solving 90% of the problem. I'll publish a branch with those over the next few days/weeks and see if I can make any headway.

You'll need to install the community version of Electron if you wish to attempt a fix yourself, you'll need to modify the build scripts (copy the one for Android, and and replace with the community electron for the open command, and the sync commands).
