### ISSUE TITLE
Error / warning in Chrome DevTools

### ISSUE THREAD

**Issue by paolodina** [drannex42/svelte-capacitor#26]
Hi! I'm trying the template and I noted something like the following in dev tools console panel.

![image](https://user-images.githubusercontent.com/1157401/167244779-f83cc7d4-7565-406f-b084-806e4803d2f5.png)

The output of the console where I run `npm run dev:start` also says:

> [svelte-preprocess] Deprecation notice: using 'lang="typescript"' is no longer recommended and will be removed in the next major version. Please use 'lang="ts"' instead.
10:05:08 AM [vite-plugin-svelte] /home/paolo/svelte-capacitor/src/App.svelte:9:1 No scopable elements found in template. If you're using global styles in the style tag, you should move it into an external stylesheet file and import it in JS. See https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#where-should-i-put-my-global-styles.

> 10:05:08 AM [vite] hmr update /src/App.svelte
10:05:08 AM [vite-plugin-svelte] /home/paolo/svelte-capacitor/src/pages/index.svelte:7:4 A11y: <img> element should have an alt attribute

> files in the public directory are served at the root path.
Instead of /assets/favicon/site.webmanifest, use /favicon/site.webmanifest.

Is it something worth a fix?

**Comment by macleod-ee** [comment]
re:ts :: Yes, this should be updated, it will soon. typescript -> ts. 

re:errors :: need to add a site.webmanifest, not sure why its needed to begin with though. 

re:a11y :: All images should as a good practice have an alt tag added,  oversight mostly.
