### ISSUE TITLE
[Question] Using https with live reload

### ISSUE THREAD

**Issue by Etchelon** [drannex42/svelte-capacitor#27]
Hello,
I'm not directly using this template but since you guys say it's production ready, I'd like to ask for advice on how to use https with the live reload functionality.
I need https because I'm using auth0 libs, which will throw when `window.crypto.subtle` is undefined (due to not being on a secure origin).
I set `server.https: true` in `vite.config.ts`.
Then I tried all possible flags in `ionic cap run android` to no avail. If I use `--livereload-url=https://192.168.1.245:3000`, the Android webview says it cannot load due to a net error. The html is empty and the network tab in Chrome devtools shows no traffic at all when reloading.
I'm out of ideas. I can ofc develop on the web and just bundle the android/ios final apps, 99% of the things should be the same, but even for small functionalities it's very time consuming to rerun `cap run android` every time, when you don't have live reload...
Thanks in advance and thanks for this template which served as inspiration! 👍

**Comment by macleod-ee** [comment]
Sounds like a cert error, if you are using `server.https: true`, then you likely need to proxy the result with an accompanying webcert. 

This is a ready-made plugin for vite to provision those certs on localhost: https://github.com/liuweiGL/vite-plugin-mkcert. If you follow the Quick Start guide it's really quite easy to use (add plugin, set server.https: true, you're already most of the way there!)
