### ISSUE TITLE
rollup just exits instantly

### ISSUE THREAD

**Issue by koo5** [drannex42/svelte-capacitor#3]
i had to bump up some dependencies versions to fix this:
https://github.com/koo5/svelte-capacitor/commit/79d8b97d925d5af43c2a0bb15b3a3b5316d0422f

**Comment by macleod-ee** [comment]
That should be fixed in the latest version forthcoming. Sorry for being so delayed, been a bit busy! Happy you could figure it out pretty quickly it seems.

**Comment by macleod-ee** [comment]
New version fixes this as we no longer depend on Rollup and have switched to using Vite, I realize it's been a few months but I have been busier than I ever thought I would be!
