### ISSUE TITLE
Update rollup configs and versions to sync changes with svelte/template

### ISSUE THREAD

**Issue by lucianoratamero** [drannex42/svelte-capacitor#4]
Hello, awesome svelters o/

When testing this project, I found out a couple of things that would be nice to change :]

The first one is: since last November, with `rollup-plugin-svelte`'s v7, the svelte plugin for rollup offloads CSS handling to rollup by default.
That means that, if we were to use new versions of the `rollup-plugin-svelte`, the build CSS file would not be created. :/

To fix that, and to sync up the changes from `svelte/template`, we could offload CSS to another plugin. 
`svelte/template` uses `rollup-plugin-css-only` for that.

I already have all updates working on a test app locally, so I could open a PR, if you want :]
I found out another issue (and possible fix), so I'll be opening another discussion as well.

As always, thanks for the hard work!

**Comment by macleod-ee** [comment]
I would absolutely love to merge that PR. Send it over, I'll take a look.

**Comment by macleod-ee** [comment]
I'll close this out as I see your PR is in the queue.
