### ISSUE TITLE
Issues setting up livereload

### ISSUE THREAD

**Issue by lucianoratamero** [drannex42/svelte-capacitor#5]
Hello again o/
I'm a bit of a noob on the mobile dev space, so if this issue doesn't make sense, please let me know!

When testing this project, everything worked beautifully, but I discovered that livereload didn't seem to work out of the box.
The livereload script always sent a `Failed to load resource: net::ERR_CONNECTION_REFUSED` error on the network tab when I was debugging the app, and refused to be loaded.
It works fine when accessing the app via browser, though so it was really weird.

After digging up a bit on capacitor's docs, I found that [the integration with non-ionic apps is kind of manual](https://capacitorjs.com/docs/guides/live-reload#using-with-framework-clis).
I'm guessing that this was the reason for the need to pass the `url` key on the `capacitor.config.json` file.
It wasn't clear to me, though, which URL I should put there.

Then, after a bit of fiddling, I understood that I should've been passing the `sirv` URL (started up by `npm run serve:capacitor`) instead of the URL generated by `npm run autobuild`.
But since they both run servers, and `autobuild` starts up faster than `serve:capacitor` on my PC, when `serve:capacitor` starts, it assigns itself a random port to run (always around 35000).
And that means I can't really know which port it will run at, so I could put it on my `url` config for capacitor.

*(phew)*

So, what I did locally was to add a `--port 5001` arg to the `serve:capacitor` npm script (to make it static), then find out my local IP with `ifconfig`, and finally set up the `url` setting with `http://my-local-ip:5001`.
With that, livereload started working again. :tada: 

My suggestions about this issue would be to:
- add the `--port 5001` to the `serve:capacitor` npm script;
- change the default `url` key to use `5001` instead of `PORT`;
- and improve the docs a bit to make it a bit clearer on what's going on, and why setting up your local IP is needed to set up livereload.

As always, I'd be glad to open a PR for that, and thanks for the hard work!

**Comment by macleod-ee** [comment]
I've added the changes you suggested, great ideas all around.
