### ISSUE TITLE
Use `http://10.0.2.2:5001` as server URL alternative for android development

### ISSUE THREAD

**Issue by lucianoratamero** [drannex42/svelte-capacitor#8]
**Related to:** #5

Hi again!

After digging up a bit more about Android development, I found out that Android Studio adds `10.0.2.2` as a proxy to `127.0.0.1`.
That means that, if you're only targeting Android (as I am), you wouldn't need to configure anything at all on `capacitor.config.json` to enable live reloading. I've tested it locally and works beautifully. :]

I'm thinking about adding a couple of comments on `capacitor.config.json` and `README.md` to make things easier for Andoid devs.
Woking on a PR right now, but feel free to reject it if you don't think it's a good idea!

**Comment by lucianoratamero** [comment]
Oh, of course, JSON doesn't support comments =_=
I'll add some docs on README, then.

**Comment by macleod-ee** [comment]
That works! 10.0.2.2 works better in most cases, since everything gets forwarded properly. 

Yes, one of the biggest qualms I have with JSON is that it doesn't have support for comments, which is tragically an oversight.

**Comment by ak4zh** [comment]
Why not use `capacitor.config.ts`

```js
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
	appId: 'com.svelte.capacitor', // TODO: add your app id
	appName: 'Svelte Capacitor',
	webDir: 'public',
	server: {
        	// comments
		"url": "http://10.0.2.2:5001",
		"cleartext": true
	}
};

export default config;
```
